apiVersion: apps/v1
kind: Deployment
metadata:
  name: host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: host
    spec:
      containers:
      - name: host
        image: public.ecr.aws/l4v6k6q7/f9ba36233aa813e998494e53ac41efa0_host:latest
        ports:
        - containerPort: 80