apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: users-web
    spec:
      containers:
      - name: users-web
        image: public.ecr.aws/l4v6k6q7/689289bfd7b0db6b706123cfa0b95825_users_web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: users-database-connection-string
              key: database_url
