apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: public.ecr.aws/l4v6k6q7/d59985bd7579cc56b43532c0c04135b1_auth:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: users-database-connection-string
              key: database_url
