apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/(sign_up|login)
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 80
      - path: /api/(projects.*)
        pathType: Prefix
        backend:
          service:
            name: projects
            port:
              number: 80
      - path: /api/(users.*)
        pathType: Prefix
        backend:
          service:
            name: users
            port:
              number: 80
      - path: /api/(files.*)
        pathType: Prefix
        backend:
          service:
            name: files
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port: 
              number: 80