apiVersion: v1
kind: Pod
metadata:
  name:  files-migrate
spec:
  containers:
  - name: files-migrate
    image: public.ecr.aws/l4v6k6q7/bfb61b46c7b497a70d89503e3f401cf0_files_migrations:latest
    env:
    - name: DATABASE_URL
      valueFrom: 
        secretKeyRef:
          name: files-database-connection-string
          key: database_url
  restartPolicy: Never