apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: projects-web
    spec:
      containers:
      - name: projects-web
        image: public.ecr.aws/l4v6k6q7/609e6f97dc3bd7a240c3fc0587448b72_projects_web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: projects-database-connection-string
              key: database_url
