apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: storage-volume