apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-web
    spec:
      containers:
      - name: auth-web
        image: public.ecr.aws/l4v6k6q7/d59985bd7579cc56b43532c0c04135b1_auth_web:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: users-database-connection-string
              key: database_url
        - name: HMAC_KEY
          valueFrom: 
            secretKeyRef:
              name: auth-hmac-key
              key: hmac_key
